### ISSUE TITLE
Configuration error when running tests.

### ISSUE THREAD

**Issue by corentindrouet** [esnext-coverage/esnext-coverage#1]
When trying to run tests with mocha like this:
- sudo node_modules/mocha/bin/_mocha -r esnext-coverage tests/api/bootstrap.test.js tests/unit/*_/_.js

An error appear:
node_modules/esnext-coverage/lib/esnext-coverage.js:11
  only: esnextcoverageConfig.only
TypeError: Cannot read property 'only' of undefined

I supposed that a config file is needed, but i didn't find it.
I fail to find a documentation for configuring this file.

**Comment by olegskl** [comment]
Hello. Thanks for reporting this.

You are correct. Currently, a configuration is required to run the coverage. Unfortunately, this is not documented yet. I'm hoping to fix this in the coming days.

You can create an `.esnextcoveragerc` file with the following contents:

``` json
{
  "only": "src/*.js",
  "reporters": [
    {"formatter": "text", "console": true},
    {"formatter": "html", "outFile": "reports/coverage/coverage.html"}
  ]
}
```

Or add the following to your `package.json`:

``` json
"esnextcoverage": {
  "only": "src/*.js",
  "reporters": [
    {"formatter": "text", "console": true},
    {"formatter": "html", "outFile": "reports/coverage.html"}
  ]
}
```

The above configuration implies that you have "text" and "html" formatters installed:

``` sh
npm install --save-dev esnext-coverage-format-text esnext-coverage-format-html
```

There is an [esnext-coverage-usage-examples](https://github.com/esnext-coverage/esnext-coverage-usage-examples) repository with usage examples.

**Comment by corentindrouet** [comment]
Really thanks, it's seems to work. :)
